/**
 * Writes the sync Worker's deploy config, binding its D1 database by id (#391).
 *
 *     node scripts/d1-binding.ts <database-name> <wrangler.jsonc> <out>
 *
 * The tracked `wrangler.jsonc` binds the database by name alone, so no id is
 * ever copied in by hand (#357). Deployed that way, wrangler 4.145 reuses the
 * id of the binding already on the Worker (`D1Handler.canInherit`) and fails
 * with 7404 once that database has been deleted and recreated. A binding that
 * carries `database_id` is "fully specified" and skips that path, so the
 * deploy resolves the id by name from `wrangler d1 list --json` and writes a
 * copy of the config with the id added, beside the original so its relative
 * paths still resolve, and git-ignored so the id never reaches a tracked file.
 *
 * Run from the repository root, after `ensure-d1.ts` has made sure the
 * database exists.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  applyEdits,
  modify,
  parse,
  type ParseError,
  printParseErrorCode,
} from 'jsonc-parser';
import { databaseList, LIST, type Wrangler, wranglerCli } from './ensure-d1';

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

/** The id of the one database named `name` in `wrangler d1 list --json`. */
export function databaseId(listJson: string, name: string): string {
  const named = databaseList(listJson).filter(
    (entry) => isRecord(entry) && entry['name'] === name,
  );
  const ids = named.map((entry) =>
    isRecord(entry) ? entry['uuid'] : undefined,
  );
  if (ids.length === 0)
    throw new Error(`no D1 database named ${name} in wrangler d1 list --json`);
  if (ids.length > 1)
    throw new Error(
      `${String(ids.length)} D1 databases are named ${name} (${ids.map(String).join(', ')}): delete the one not in use`,
    );
  const [id] = ids;
  if (typeof id !== 'string' || !UUID.test(id))
    throw new Error(`wrangler d1 list --json printed ${name} with no uuid`);
  return id;
}

/** The config's `d1_databases`, read strictly: comments and trailing commas only. */
function d1Bindings(config: string): unknown[] {
  const errors: ParseError[] = [];
  const parsed: unknown = parse(config, errors, { allowTrailingComma: true });
  if (errors.length > 0)
    throw new Error(
      `the config is not valid JSONC: ${errors.map((error) => `${printParseErrorCode(error.error)} at offset ${String(error.offset)}`).join(', ')}`,
    );
  if (!isRecord(parsed)) throw new Error('the config is not an object');
  const bindings = parsed['d1_databases'];
  return Array.isArray(bindings) ? bindings : [];
}

/**
 * The config text with `database_id: id` added to the binding of the database
 * named `name`, and nothing else changed.
 */
export function withDatabaseId(
  config: string,
  name: string,
  id: string,
): string {
  const bindings = d1Bindings(config);
  const matches = bindings.flatMap((binding, index) =>
    isRecord(binding) && binding['database_name'] === name
      ? [{ index, binding }]
      : [],
  );
  const [match] = matches;
  if (match === undefined)
    throw new Error(`the config binds no D1 database named ${name}`);
  if (matches.length > 1)
    throw new Error(`the config binds ${name} ${String(matches.length)} times`);
  const { index, binding } = match;
  if (binding['database_id'] !== undefined)
    throw new Error(
      `the config already binds ${name} to ${JSON.stringify(binding['database_id'])}: the tracked file binds by name only`,
    );
  return applyEdits(
    config,
    modify(config, ['d1_databases', index, 'database_id'], id, {
      formattingOptions: { insertSpaces: true, tabSize: 2, eol: '\n' },
    }),
  );
}

const GENERATED =
  '// GENERATED by scripts/d1-binding.ts at deploy (#391), from wrangler.jsonc. Not tracked; edit wrangler.jsonc.';

/**
 * Resolves `name`'s id, writes `source` with that id to `out`, reads `out`
 * back, and returns the id. Nothing is written unless every step before it
 * succeeds.
 */
export function bindDeployConfig(
  name: string,
  source: string,
  out: string,
  wrangler: Wrangler,
): string {
  if (resolve(source) === resolve(out))
    throw new Error(`will not write over ${source}, the config it reads`);
  const id = databaseId(wrangler(LIST), name);
  const written = `${GENERATED}\n${withDatabaseId(readFileSync(source, 'utf8'), name, id)}`;
  writeFileSync(out, written);
  const readBack = d1Bindings(readFileSync(out, 'utf8')).filter(
    (binding) =>
      isRecord(binding) &&
      binding['database_name'] === name &&
      binding['database_id'] === id,
  );
  if (readBack.length !== 1)
    throw new Error(`${out} was written, but does not bind ${name} to ${id}`);
  return id;
}

if (import.meta.main) {
  const [name, source, out] = process.argv.slice(2);
  if (name === undefined || source === undefined || out === undefined)
    throw new Error(
      'usage: node scripts/d1-binding.ts <database-name> <wrangler.jsonc> <out>',
    );
  const id = bindDeployConfig(name, source, out, wranglerCli);
  console.log(`✓ ${out} binds D1 database ${name} to ${id}`);
}
