import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Generates THIRD-PARTY-NOTICES.md from the lockfile (#26 AC11).
 *
 * Every package in the production dependency closure of a shipped workspace
 * is listed with its version and licence, followed by each distinct LICENSE
 * and NOTICE text verbatim. Identical texts are printed once, with the
 * packages they cover. Run `npm run notices` after any dependency change; a
 * unit test fails while the committed file differs from this output.
 */

export interface LockPackage {
  version?: string;
  license?: string;
  dependencies?: Record<string, string>;
}

export interface Lockfile {
  packages: Record<string, LockPackage>;
}

export interface Bundled {
  name: string;
  version: string;
  license: string;
  /** The package's lockfile key, which is also its path from the repo root. */
  path: string;
}

/** Workspaces whose dependencies end up inside a shipped build. */
export const SHIPPED_WORKSPACES = ['packages/core'] as const;

const FILE_PATTERNS = {
  licence: /^licen[cs]e(\.(md|txt))?$/i,
  notice: /^notice(\.(md|txt))?$/i,
} as const;

/**
 * The licence or notice file among a package's file names, matched without
 * regard to case. Asking the filesystem for `LICENSE.md` finds `license.md`
 * on macOS and not on Linux: `ms` 2.0.0 ships `license.md`, and CI failed on
 * exactly that. Candidates are sorted (no extension, then .md, then .txt,
 * then by name), because directory listing order differs between
 * filesystems too.
 */
export function pickFile(
  names: readonly string[],
  kind: keyof typeof FILE_PATTERNS,
): string | undefined {
  const rank = (name: string) =>
    name.includes('.') ? (/\.md$/i.test(name) ? 1 : 2) : 0;
  return names
    .filter((name) => FILE_PATTERNS[kind].test(name))
    .sort((a, b) => rank(a) - rank(b) || (a < b ? -1 : a > b ? 1 : 0))[0];
}

/** Finds `name` the way Node does: nearest node_modules first, then upward. */
function resolve(lock: Lockfile, from: string, name: string): string {
  let dir = from;
  for (;;) {
    const key = `${dir === '' ? '' : `${dir}/`}node_modules/${name}`;
    if (key in lock.packages) return key;
    if (dir === '') {
      throw new Error(
        `${name}, needed by ${from}, is not in package-lock.json`,
      );
    }
    const parent = dir.lastIndexOf('/node_modules/');
    dir = parent === -1 ? '' : dir.slice(0, parent);
  }
}

/** The production dependency closure of every shipped workspace, by name. */
export function bundledPackages(lock: Lockfile): Bundled[] {
  const seen = new Map<string, Bundled>();
  const queue: string[] = [...SHIPPED_WORKSPACES];
  for (let from = queue.shift(); from !== undefined; from = queue.shift()) {
    for (const name of Object.keys(lock.packages[from]?.dependencies ?? {})) {
      const path = resolve(lock, from, name);
      if (seen.has(path)) continue;
      const entry = lock.packages[path];
      if (entry?.version === undefined || entry.license === undefined) {
        throw new Error(
          `${path} has no version or licence in package-lock.json`,
        );
      }
      seen.set(path, {
        name,
        version: entry.version,
        license: entry.license,
        path,
      });
      queue.push(path);
    }
  }
  return [...seen.values()].sort(
    (a, b) =>
      a.name.localeCompare(b.name, 'en') ||
      a.version.localeCompare(b.version, 'en'),
  );
}

function readText(
  root: string,
  path: string,
  kind: keyof typeof FILE_PATTERNS,
): string | undefined {
  const file = pickFile(readdirSync(join(root, path)), kind);
  if (file === undefined) return undefined;
  return readFileSync(join(root, path, file), 'utf8')
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .map((line) => line.trimEnd())
    .join('\n')
    .trim();
}

/** A code fence longer than any backtick run inside the text. */
function fence(text: string): string {
  const longest = Math.max(
    0,
    ...[...text.matchAll(/`+/g)].map((m) => m[0].length),
  );
  return '`'.repeat(Math.max(3, longest + 1));
}

export function renderNotices(lock: Lockfile, root: string): string {
  const packages = bundledPackages(lock);
  const texts = new Map<string, string[]>();
  for (const pkg of packages) {
    const licence = readText(root, pkg.path, 'licence');
    if (licence === undefined) {
      throw new Error(
        `${pkg.name} ships no LICENSE file; supply its licence text by hand`,
      );
    }
    const notice = readText(root, pkg.path, 'notice');
    for (const text of notice === undefined ? [licence] : [licence, notice]) {
      texts.set(text, [...(texts.get(text) ?? []), pkg.name]);
    }
  }

  const lines = [
    '# Third-party notices',
    '',
    'Generated by `npm run notices` from package-lock.json. Do not edit by hand.',
    '',
    'The production dependency closure of every workspace that a shipped',
    'Yawelo Idle build bundles. A bundler may leave some of these out; listing',
    'the whole closure errs on the side of attribution. Each licence and NOTICE',
    'text they ship follows the list, printed once with the packages it covers.',
    '',
    '## Packages',
    '',
    ...packages.map((p) => `- \`${p.name}\` ${p.version} (${p.license})`),
    '',
    '## Licence and notice texts',
  ];
  let index = 0;
  for (const [text, names] of texts) {
    index += 1;
    const f = fence(text);
    lines.push(
      '',
      `### Text ${String(index)}`,
      '',
      `Covers: ${names.map((n) => `\`${n}\``).join(', ')}.`,
      '',
      `${f}text`,
      text,
      f,
    );
  }
  return `${lines.join('\n')}\n`;
}

if (import.meta.main) {
  const lock = JSON.parse(
    readFileSync('package-lock.json', 'utf8'),
  ) as Lockfile;
  writeFileSync('THIRD-PARTY-NOTICES.md', renderNotices(lock, '.'));
}
