/**
 * Every scope holding an absence search that proves nothing about its
 * population, by `file › test title as written` (or the named function), with
 * how many (#361). Measured when the meta-guard landed. A search is proved by
 * a recorded floor on the population its `of:` names, checked in the same
 * scope, or, for an input left empty on purpose, by againstControl.
 *
 * Checked for equality both ways by `floorless-searches.test.ts`: a new
 * unproved search fails, and so does a converted one until its entry is
 * lowered. It only shrinks.
 */
export const UNPROVED: Readonly<Record<string, number>> = {
  'packages/bots/pacing/pacing.test.ts › (a) %s sets sail for the first time after 30 to 60 minutes': 1,
  'packages/bots/pacing/pacing.test.ts › (b) the Casual Learner reaches each later destination 1 to 3 days after the one before': 1,
  'packages/bots/pacing/pacing.test.ts › (c) the Casual Learner reaches the finale in 3 to 5 weeks': 1,
  'packages/bots/pacing/pacing.test.ts › (d) the Idler reaches the finale within 10 weeks': 1,
  'packages/bots/pacing/pacing.test.ts › (e) every open of %s offers a meaningful decision': 1,
  'packages/bots/pacing/pacing.test.ts › (f) learning pays: the Casual Learner reaches the finale at least 20% sooner than the Non-learner': 1,
  'packages/bots/pacing/pacing.test.ts › (f) the Diligent Learner finishes no later than the Casual Learner, nor the Casual Learner than the Idler': 1,
  'packages/bots/pacing/pacing.test.ts › (g) clicking never beats idling: the Clicker takes at least 95% of the Casual Learner’s time to reach each sail’s goal': 1,
  'packages/bots/pacing/pacing.test.ts › (h) %s meets no NaN, negative or infinite value': 1,
  'packages/bots/test/calibrate.test.ts › fits each goal so its sail lands by its target and within 0.01 days of it': 1,
  'packages/bots/test/calibrate.test.ts › fits each later goal about a gap of decades above the one before': 1,
  'packages/bots/test/calibrate.test.ts › shows the measure only the goals fitted so far, the rest unreachable': 3,
  'packages/bots/test/calibrate.test.ts › writes each goal with 3 significant figures': 1,
  'packages/bots/test/player.test.ts › a Non-learner answers none': 1,
  'packages/bots/test/player.test.ts › a learner answers every due review': 1,
  'packages/bots/test/player.test.ts › buys until nothing is affordable': 1,
  'packages/bots/test/player.test.ts › reports no decision when nothing is affordable, due, free or available': 1,
  'packages/bots/test/player.test.ts › sets sail at the first check the goal is met, buying nothing in it': 1,
  'packages/bots/test/player.test.ts › taps Listen while it owns nothing and nothing is affordable, then buys': 1,
  'packages/bots/test/player.test.ts › the Random Buyer buys until nothing is affordable, in its own order': 1,
  'packages/bots/test/run.test.ts › finds nothing in a new game’s view': 1,
  'packages/bots/test/run.test.ts › judges a return 15 minutes after each of the first day’s 3 opens': 2,
  'packages/bots/test/run.test.ts › plays the Casual Learner’s first day: 3 opens, sails timed from the first open': 3,
  'packages/bots/test/run.test.ts › times each goal from when the Understanding earned that run reached it: after the sail before, no later than its own sail, and for the Idler hours before an open lets it sail': 2,
  'packages/bots/test/streams.test.ts › draw floats in [0, 1)': 1,
  'packages/bots/test/streams.test.ts › is a whole, positive number of milliseconds': 1,
  'packages/bots/test/streams.test.ts › is always correct at R = 1': 1,
  'packages/bots/test/streams.test.ts › is never correct at R = 0': 1,
  'packages/bots/test/streams.test.ts › keeps opens at least an hour apart, from one day to the next too': 1,
  'packages/bots/test/streams.test.ts › places each open in its own slot of waking hours': 1,
  'packages/bots/test/streams.test.ts › places later opens at whole seconds of waking hours, in order': 1,
  'packages/bots/test/targets.test.ts › accepts a 15-minute return where only Practice is on offer (operator, 2026-10-04)': 1,
  'packages/bots/test/targets.test.ts › holds at gaps just inside 1 and 3 days': 2,
  'packages/bots/test/targets.test.ts › holds just before day 70': 1,
  'packages/bots/test/targets.test.ts › holds just inside 30 and 60 minutes': 2,
  'packages/bots/test/targets.test.ts › holds just inside day 21 and day 35': 2,
  'packages/bots/test/targets.test.ts › holds just over 95% of the Casual Learner’s time': 1,
  'packages/bots/test/targets.test.ts › holds when Diligent ≤ Casual ≤ Idler, ties included': 1,
  'packages/bots/test/targets.test.ts › holds when every open offered one': 1,
  'packages/bots/test/targets.test.ts › holds when the Casual Learner finishes just over 20% sooner': 1,
  'packages/bots/test/targets.test.ts › holds with no insane value': 1,
  'packages/bots/test/targets.test.ts › judges a return after every open when no finale ends the run': 1,
  'packages/bots/test/targets.test.ts › judges when each goal was reached, not the open the sail waited for (operator, 2026-10-04)': 1,
  'packages/bots/test/targets.test.ts › lets a variant cross by one open: a sail one open sooner would have kept within 3 days (operator, 2026-10-04)': 1,
  'packages/core/test/automation.test.ts › buys nothing when nothing is owned and nothing is affordable': 1,
  'packages/core/test/cards.test.ts › is not shown while no card is held': 1,
  'packages/core/test/grammar.test.ts › is empty with no node owned': 1,
  'packages/core/test/hash.test.ts › changes when any numeric field moves by one ulp': 1,
  'packages/core/test/ladder.test.ts › carries no tier into the course core plays': 1,
  'packages/core/test/log.test.ts › a log with a refused event inserted replays to the state without it': 1,
  'packages/core/test/review.test.ts › is empty when nothing is due': 2,
  "packages/core/test/sail.test.ts › a sail from destination ${String(i)} goes to ${IDS[i + 1] ?? ''}": 1,
  'packages/core/test/sail.test.ts › never needs a review: unreviewed words and no Insight still sail (D1)': 1,
  'packages/core/test/sail.test.ts › owns no Encounters and holds only the starting grant, with nothing spent': 1,
  'packages/core/test/sail.test.ts › resets exactly the Encounters owned and the Understanding held': 1,
  'packages/core/test/shop.test.ts › is not affordable before grammar opens, however much Insight is held': 1,
  'packages/core/test/shop.test.ts › offers nothing while every open slot is busy': 1,
  'packages/core/test/shop.test.ts › stays on offer with nothing else affordable, as Practice costs nothing': 1,
  'packages/core/test/words.test.ts › is refused when the pool is empty, never reaching a later destination': 1,
  'packages/lockdown/test/lockdown.test.ts › challenges %s on a non-prod host and never serves': 2,
  'packages/lockdown/test/lockdown.test.ts › challenges every request when the password is not configured': 1,
  'packages/lockdown/test/lockdown.test.ts › serves blocking robots.txt on a non-prod host': 1,
  'packages/lockdown/test/lockdown.test.ts › serves blocking robots.txt on a non-prod host without credentials': 1,
  'tests/unit/burn-down.test.ts › ignores entries left over once their items are taken': 1,
  'tests/unit/burn-down.test.ts › leaves nothing when every item is matched': 1,
  'tests/unit/ci-scope.test.ts › a commit changing nothing is full (an empty diff)': 1,
  'tests/unit/ci-scope.test.ts › is full for a mix with the code path first, judging both': 1,
  'tests/unit/ci-scope.test.ts › is full for an empty diff, saying there was nothing to judge': 1,
  'tests/unit/ci-scope.test.ts › reads an empty diff as no changes': 1,
  'tests/unit/core-determinism-lint.test.ts › is scoped to packages/core/src: the same code elsewhere is not banned': 2,
  'tests/unit/core-determinism-lint.test.ts › label': 1,
  'tests/unit/core-determinism-lint.test.ts › lint': 1,
  'tests/unit/every-commit-ci.test.ts › checks out that ref, the event’s own commit when it is empty': 1,
  'tests/unit/every-commit-ci.test.ts › checks out the pull request’s head with its whole history': 1,
  'tests/unit/every-commit-ci.test.ts › judges with the verdict script, given the list, both results and a token': 1,
  'tests/unit/every-commit-ci.test.ts › lists the commits between the pull request’s base and head': 1,
  'tests/unit/every-commit-ci.test.ts › runs Node from .nvmrc, with no npm ci': 1,
  'tests/unit/every-commit.test.ts › ignores the run’s other jobs': 1,
  'tests/unit/every-commit.test.ts › passes a list of exactly the matrix limit': 1,
  'tests/unit/every-commit.test.ts › reads no output as no commits': 1,
  'tests/unit/every-commit.test.ts › reads no output, from a list job that failed, as no commits': 1,
  'tests/unit/one-test-per-case.test.ts › classifies every call on it and test, refusing by name what it cannot read': 1,
  'tests/unit/one-test-per-case.test.ts › keeps no burn-down entry that has already been split': 1,
  'tests/unit/one-test-per-case.test.ts › leaves alone ${what}': 1,
  'tests/unit/one-test-per-case.test.ts › loops no known population inside a test beyond the burn-down list': 1,
  'tests/unit/one-test-per-case.test.ts › reads a Playwright annotation inside a test as no test': 1,
  'tests/unit/one-test-per-case.test.ts › reads a describe modifier as no test and refuses nothing': 1,
  'tests/unit/one-test-per-case.test.ts › reads at least one test in every file whose text holds a test call': 1,
  'tests/unit/workflow-secrets.test.ts › accepts a secret in a job that declares the dev environment': 1,
  'tests/unit/workflow-secrets.test.ts › accepts the long form, environment: { name: production, url }': 1,
  'tests/unit/workflow-secrets.test.ts › ignores GITHUB_TOKEN, which GitHub mints per run': 1,
  'tests/unit/workflow-secrets.test.ts › is not satisfied or tripped by a comment': 1,
  'tests/unit/workflow-secrets.test.ts › no secret is read outside a protected environment': 1,
  'tests/unit/workflow-secrets.test.ts › reads a reference in every workflow whose text names a stored secret (Refs #82)': 1,
  'tests/unit/workflow-secrets.test.ts › scans every workflow, and every one has jobs': 1,
  'tests/unit/workflow-timeouts.test.ts › accepts a call to a local reusable workflow, whose own jobs carry the timeouts': 1,
  'tests/unit/workflow-timeouts.test.ts › accepts a job with a timeout inside the bound': 1,
  'tests/unit/workflow-timeouts.test.ts › accepts the bound itself, ${String(MAX_TIMEOUT_MINUTES)} minutes': 1,
  'tests/unit/workflow-timeouts.test.ts › checks every job it finds (liveness)': 1,
  'tests/unit/workflow-timeouts.test.ts › every job has a timeout of at most 30 minutes': 1,
  'tests/unit/workflow-timeouts.test.ts › every reusable-workflow call names a workflow that is scanned here': 1,
};
